version: '3.7'

networks:
  backend_network:
  redis_network:
  database_network:

services:

  backend:
    container_name: real_state_backend
    restart: on-failure
    build: .
    env_file: .env
    command:  uwsgi --socket=:8002 --module=project.wsgi:application --py-autoreload=1
    volumes:
      - .:/app
      - ./static:/app/static
    networks:
      - backend_network
      - redis_network
      - database_network

  redis:
    image: redis:latest
    restart: always
    volumes:
      - ./setup/docker/redis-data:/data
    networks:
      - redis_network
    command: redis-server
    ports:
      - '6390:6379'

  database:
    image: kartoza/postgis:13.0
    volumes:
      - ./setup/docker/postgres:/var/lib/postgresql/12/main
    env_file: .env
    restart: on-failure
    networks:
      - database_network

  nginx:
    image: nginx:1.15.0
    volumes:
      - ./setup/nginx:/etc/nginx/conf.d
      - ./static:/app/static
    networks:
      - backend_network
    ports:
      - '4500:80'
    logging:
      driver: 'none'

  worker:
    build: .
    volumes:
      - .:/app
    env_file: .env
    restart: on-failure
    command: celery -A project worker --concurrency=10 -l info
    networks:
      - redis_network
      - database_network